- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      script: hello.py # run script
      args:
        executable: python3
      register: output # output ze skryptu z print()
    - debug: var=output.stdout_lines # output ze skryptu z print()
