- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      script: hello.py
      args:
        executable: python3
      register: output
    - debug: var=output.stdout_lines
